# Project: Project7
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main5.o
LINKOBJ  = main5.o
LIBS     = -L"E:/zzl/C++/DEV/Dev-Cpp/MinGW64/lib" -L"E:/zzl/C++/DEV/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/zzl/C++/DEV/Dev-Cpp/MinGW64/include" -I"E:/zzl/C++/DEV/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/zzl/C++/DEV/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/zzl/C++/DEV/Dev-Cpp/MinGW64/include" -I"E:/zzl/C++/DEV/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/zzl/C++/DEV/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/zzl/C++/DEV/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project7.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main5.o: main5.cpp
	$(CPP) -c main5.cpp -o main5.o $(CXXFLAGS)
